export const TYPES = {
    GET_HISTORICO_ALGORITMOS_REQUESTED: '@detalhesUsuario/GET_HISTORICO_ALGORITMOS',
    GET_HISTORICO_ALGORITMOS_SUCCEEDED: '@detalhesUsuario/GET_HISTORICO_ALGORITMOS',
    GET_HISTORICO_ALGORITMOS_FAILED: '@detalhesUsuario/GET_HISTORICO_ALGORITMOS',
};